### ISSUE TITLE
Unable to read from Power Apps Data Lake Export (Athena)

### ISSUE THREAD

**Issue by adessoreimer** [Azure/spark-cdm-connector#17]
I am trying to access CDM data in Databricks that was exported with the new Power Apps GA feature "Export to Data Lake" (Athena). I can successfully mount and unmount the ADLS2 storage with the CDM folder in Databricks but when using the CDM connector it throws an exception:

val df = spark.read.format("com.microsoft.cdm")
  .option("storage", storageAccountName)
  .option("container", container)
  .option("manifest", "model.json")
  .option("entity", "contact")
  .option("appId", appid)
  .option("appKey", appkey)
  .option("tenantId", tenantid)
  .load()

ava.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347)
	at scala.None$.get(Option.scala:345)
	at com.microsoft.cdm.utils.CDMModelReader$$anonfun$1.apply(CDMModelReader.scala:50)
	at com.microsoft.cdm.utils.CDMModelReader$$anonfun$1.apply(CDMModelReader.scala:38)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.microsoft.cdm.utils.CDMModelReader.getStructType(CDMModelReader.scala:38)
	at com.microsoft.cdm.utils.CDMModelReader.getSchema(CDMModelReader.scala:77)

**Comment by sricheta92** [comment]
Hello adessoreimer, Thanks for query. Can you share model.json file and contact entity?

**Comment by adessoreimer** [comment]
> Hello @adessoreimer, Thanks for query. Can you share model.json file and contact entity to [asksparkcdm@microsoft.com](mailto:asksparkcdm@microsoft.com)

Sure, I just shared the model.json and csv-files.

**Comment by sricheta92** [comment]
Hi @adessoreimer.  There is a problem with Decimal data declarations in a model.json file. We are working on the fix and it should be available early next week.

**Comment by trbran** [comment]
Using the 0.9 version of the connector fixed it for my Athena-based data :-)

**Comment by adessoreimer** [comment]
Thank you for providing the fix. All entities can be read now.
